project_id = "fhaukvjpthkftfxfmnhm"

[functions.google-places]
verify_jwt = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm your DiRent signup"
content_path = "./templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your DiRent password"
content_path = "./templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your DiRent login link"
content_path = "./templates/magic_link.html"
